DROP TABLE IF EXISTS ODONTOLOGOS
;
CREATE TABLE ODONTOLOGOS(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  MATRICULA INT NOT NULL,
  NOMBRE VARCHAR(100) NOT NULL,
  APELLIDO VARCHAR(100) NOT NULL
  )
;
INSERT INTO ODONTOLOGOS
(MATRICULA, NOMBRE, APELLIDO) VALUES (50, 'MONICA', 'DIAZ')
;
INSERT INTO ODONTOLOGOS
(MATRICULA, NOMBRE, APELLIDO) VALUES (20, 'ALICIA', 'HERNANDEZ')
;
INSERT INTO ODONTOLOGOS
(MATRICULA, NOMBRE, APELLIDO) VALUES (12, 'PEPITO', 'PEREZ')
;
INSERT INTO ODONTOLOGOS
(MATRICULA, NOMBRE, APELLIDO) VALUES (15, 'SOFIA', 'VERGARA')